### 1. 测试计算订单优惠价格
POST http://localhost:20002/calculator/checkout
Content-Type: application/json

{
  "products": [
    {
      "productId": 444,
      "price": 1000,
      "count": 2,
      "shopId": 555
    }
  ],
  "userId": 111,
  "couponId": 222,
  "cost": 300,
  "couponInfos": [
    {
      "id": 1,
      "templateId": 1001,
      "shopId": 555,
      "userId": 111,
      "status": 1,
      "template" : {
        "id": 1,
        "available": true,
        "rule": {
          "discount": {
            "quota": 90,
            "threshold": 1
          },
          "limitation": 5,
          "deadline": 1693576800000
        },
        "type": "2",
        "name": "Example Coupon",
        "desc": "This is an example coupon",
        "discount": 10,
        "expiryDate": "2024-12-31"
      }
    }
  ]
}

### 2. 模拟优惠计算
POST http://localhost:20002/calculator/simulate
Content-Type: application/json

{
  "products": [
    {
      "productId": 444,
      "price": 1000,
      "count": 2,
      "shopId": 555
    }
  ],
  "couponIDs": [
    1,
    2
  ],
  "couponInfos": [
    {
      "id": 1,
      "templateId": 1001,
      "shopId": 555,
      "userId": 111,
      "status": 1,
      "template" : {
        "id": 1,
        "available": true,
        "rule": {
          "discount": {
            "quota": 90,
            "threshold": 1
          },
          "limitation": 5,
          "deadline": 1693576800000
        },
        "type": "2",
        "name": "Example Coupon",
        "desc": "This is an example coupon",
        "discount": 10,
        "expiryDate": "2024-12-31"
      }
    },
    {
      "id": 2,
      "templateId": 1002,
      "shopId": 555,
      "userId": 111,
      "status": 1,
      "template" : {
        "id": 2,
        "available": true,
        "rule": {
          "discount": {
            "quota": 70,
            "threshold": 1
          },
          "limitation": 5,
          "deadline": 1693576800000
        },
        "type": "1",
        "name": "Example Coupon",
        "desc": "This is an example coupon",
        "discount": 10,
        "expiryDate": "2024-12-31"
      }
    }
  ]
}


